package EasterAssignment;
import java.awt.BorderLayout;
import java.awt.EventQueue;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.border.EmptyBorder;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.JButton;
import java.awt.Color;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import javax.swing.JTable;
import javax.swing.JTextPane;
//attributes 
public class Commuting1 extends JFrame {
	private JPanel contentPane;
	private JTextField cartxt;
	private JTextField bustxt;
	private JTextField luastxt;
	private JTextField endcartext;
	private JTextField endbustext;
	private JTextField endluastext;
//these are private to not allow anyone from outside change anything from outside the class	
	
	
	 //launch the application
	 
	public Commuting1(String[] args) {
		EventQueue.invokeLater(new Runnable() { //auto generated by design program
			public void run() {
				try {
					Commuting1 frame = new Commuting1();
					frame.setVisible(true);//shows the frame
				} catch (Exception e) {//exception if there is any errors it will catch it
					e.printStackTrace();
				}
			}	
		});
	}	
	public Commuting1() {
		setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		setBounds(100,100,450,300);
		contentPane =new JPanel();//setting up the structure of the frame
		contentPane.setBackground(new Color(255,255,255));
		contentPane.setBorder(new EmptyBorder(5,5,5,5));
		setContentPane(contentPane);
		contentPane.setLayout(null);
		
		JLabel lblCommuteByCar = new JLabel("Commute by Car           Start:");
		lblCommuteByCar.setBounds(10, 32, 183, 14);
		contentPane.add(lblCommuteByCar);//content screen
		
		JLabel lblCommuteByBus = new JLabel("Commute by Bus          Start:");
		lblCommuteByBus.setBounds(10, 88, 183, 14);
		getContentPane().add(lblCommuteByBus);
		
		JLabel lblCommuteByLuas = new JLabel("Commute by Luas        Start:");
		lblCommuteByLuas.setBounds(10, 141, 183, 14);
		getContentPane().add(lblCommuteByLuas);
		
		cartxt = new JTextField();
		cartxt.setBounds(203, 29, 40, 20);
		getContentPane().add(cartxt);//setting boundary location
		cartxt.setColumns(10);
		
		bustxt = new JTextField();
		bustxt.setBounds(203, 85, 40, 20);
		getContentPane().add(bustxt);
		bustxt.setColumns(10);
		
		luastxt = new JTextField();
		luastxt.setBounds(203, 138, 40, 20);
		getContentPane().add(luastxt);
		luastxt.setColumns(10);
		
		JButton btnEvalute = new JButton("Evalute");
		btnEvalute.addActionListener(new ActionListener() {//when the button is pressed a reaction is performed
			public void actionPerformed(ActionEvent e) {
				
				//Create an instance of car
				Activities car=new Activities(Integer.parseInt(cartxt.getText()), Integer.parseInt(endcartext.getText()));//turns text to integer and calculates start and end time of car travel

				//Create an instance of bus
				Activities bus=new Activities(Integer.parseInt(bustxt.getText()), Integer.parseInt(endbustext.getText()));				
				
				//Create an instance of luas
				Activities luas=new Activities(Integer.parseInt(luastxt.getText()), Integer.parseInt(endluastext.getText()));
				
				if(Integer.parseInt(cartxt.getText())==0&&Integer.parseInt(bustxt.getText())==0&&Integer.parseInt(luastxt.getText())==0)//adds them all together by &&
				{
					JOptionPane.showMessageDialog(null, "Wrong Values...!!!");		//if values entered are 0 a message shows up saying this			
				}else
				{
					JOptionPane.showMessageDialog(null, "I have spent "+car.timeSpent()+" by car, "+bus.timeSpent()+" by bus, "+luas.timeSpent()+" by luas");
				}
				
			}
		});
		btnEvalute.setBounds(163, 201, 112, 23);
		contentPane.add(btnEvalute);
		
		endcartext = new JTextField();
		endcartext.setColumns(10);
		endcartext.setBounds(319, 26, 47, 20);
		contentPane.add(endcartext);
		
		JLabel lblEnd = new JLabel("End:");
		lblEnd.setBounds(265, 29, 40, 14);
		contentPane.add(lblEnd);
		
		JLabel label = new JLabel("End:");//end time label
		label.setBounds(265, 88, 40, 14);
		contentPane.add(label);
		
		endbustext = new JTextField();
		endbustext.setColumns(10);
		endbustext.setBounds(319, 85, 47, 20);
		contentPane.add(endbustext);
		
		JLabel label_1 = new JLabel("End:");
		label_1.setBounds(265, 143, 40, 14);
		contentPane.add(label_1);
		
		endluastext = new JTextField();
		endluastext.setColumns(10);
		endluastext.setBounds(319, 140, 47, 20);
		contentPane.add(endluastext);
		
		
	}

	 // Launch the application.
	
	public static void main(String[] args) {
		EventQueue.invokeLater(new Runnable() {
			public void run() {
				try {
					Commuting1 frame = new Commuting1();
					frame.setVisible(true);
				} catch (Exception e) {
					e.printStackTrace();
				}
			}
		});
	}
}
//this screen is for setting up the commuting class and is this is the main screen.